crm_project/accounts/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path

from .views import (
    PassChangeView, ProfileUpdateView,
    UserContactPersonListView, UserCustomerListView,
    UserInteractionListView, UserLoginView,
    UserLogoutView, UserProjectListView,
    KeywordsView
)

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    # path('<int:pk>/private-page/', UserPrivatePageView.as_view(), name='private_page'),
    path('edit-profile/', ProfileUpdateView.as_view(), name='edit_profile'),
    path('change-password/', PassChangeView.as_view(), name='change_password'),
    path('my-customers/', UserCustomerListView.as_view(), name='my_customers'),
    path('my-projects/', UserProjectListView.as_view(), name='my_projects'),
    path('my-contacts/', UserContactPersonListView.as_view(), name='my_contacts'),
    path('my-interactions/', UserInteractionListView.as_view(), name='my_interactions'),
    path('my-keywords/', KeywordsView.as_view(), name='my_keywords'),
]

crm_project/crm_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customers.urls')),
    path('user/', include('accounts.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm_project/customers/urls.py
from django.urls import path

from .views import (
    CustomerListView, CustomerDetailView, CustomerCreateView, CustomerUpdateView, CustomerDeleteView,
    ProjectListView, ProjectDetailView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView,
    ContactPersonCreateView, ContactPersonDetailView, ContactPersonUpdateView, ContactPersonDeleteView,
    ContactCreateView, ContactUpdateView, ContactDeleteView,
    InteractionListView, InteractionDetailView, InteractionCreateView, InteractionUpdateView, InteractionDeleteView,
)

urlpatterns = [
    path('', CustomerListView.as_view(), name='customer_list'),
    path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customer_detail'),
    path('customer/create/', CustomerCreateView.as_view(), name='customer_create'),
    path('customer/<int:pk>/update/', CustomerUpdateView.as_view(), name='customer_update'),
    path('customer/<int:pk>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),
    path('customer/<int:pk>/create-project/', ProjectCreateView.as_view(), name='project_create'),
    path('customer/<int:pk>/project-list/', ProjectListView.as_view(), name='project_list'),
    path('customer/<int:pk>/contact-person-create/', ContactPersonCreateView.as_view(), name='contact_person_create'),
    path('customer/<int:pk>/contact-create/', ContactCreateView.as_view(), name='contact_create'),
    path('customer/<int:pk>/interaction-list', InteractionListView.as_view(), name='customer_interaction_list'),
    path('customer/<int:pk>/interaction-create/', InteractionCreateView.as_view(), name='interaction_create'),
    path('project/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),
    path('contact_person/<int:pk>/', ContactPersonDetailView.as_view(), name='contact_person_detail'),
    path('contact_person/<int:pk>/update/', ContactPersonUpdateView.as_view(), name='contact_person_update'),
    path('contact_person/<int:pk>/delete/', ContactPersonDeleteView.as_view(), name='contact_person_delete'),
    path('contact/<int:pk>/update/', ContactUpdateView.as_view(), name='contact_update'),
    path('contact/<int:pk>/delete/', ContactDeleteView.as_view(), name='contact_delete'),
    path('interaction/<int:pk>/', InteractionDetailView.as_view(), name='interaction_detail'),
    path('interaction/<int:pk>/update/', InteractionUpdateView.as_view(), name='interaction_update'),
    path('interaction/<int:pk>/delete/', InteractionDeleteView.as_view(), name='interaction_delete'),
]

crm_project/accounts/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Account(models.Model):
    """A model for storing extended user accounts."""
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    """: Generic user of a Django."""
    photo = models.ImageField(verbose_name='Фотография', upload_to='photo/', default='photo/no-avatar.png')
    """: A user's photo."""

    def __str__(self):
        """Return the string representation of the entry."""
        return str(self.user.username)

    def get_absolute_url(self):
        """Return the string representation of the entry."""
        return reverse('edit_profile')

    class Meta:
        verbose_name = 'Аккаунт'
        verbose_name_plural = 'Аккаунты'


class Keyword(models.Model):
    """A model for storing user's search keywords."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.CASCADE)
    """: A keyword owner."""
    word = models.CharField(max_length=20)
    """: A keyword."""

    def __str__(self):
        """Return the string representation of the entry."""
        return self.word

    class Meta:
        ordering = ['word']
        verbose_name = 'Ключевое слово'
        verbose_name_plural = 'Ключевые слова'

crm_project/customers/models.py
from ckeditor.fields import RichTextField
import datetime
import re

from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse

from accounts.models import Account


class Customer(models.Model):
    """A model for storing a list of customers."""
    company_name = models.CharField(verbose_name='Название', max_length=200)
    """: The name of a customer's company."""
    address = models.CharField(verbose_name='Адрес', max_length=200, null=True, blank=True)
    """: The address of a customer's company."""
    record_created = models.DateField(verbose_name='Дата создания записи', auto_now_add=True)
    """: Date the record was created."""
    record_last_modified = models.DateField(verbose_name='Дата последнего изменения', auto_now=True)
    """: Date the record was last modified."""
    description = RichTextField(verbose_name='Описание', null=True, blank=True)
    """: Customer description."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.SET_NULL, null=True)
    """: The manager who created the entry."""

    def __str__(self):
        """Return the string representation of the entry."""
        return self.company_name

    def get_absolute_url(self):
        """Return an url of the record's page."""
        return reverse('customer_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-pk']
        verbose_name = 'Заказчик'
        verbose_name_plural = 'Заказчики'


class Project(models.Model):
    """A model for storing a list of projects."""
    name = models.CharField(verbose_name='Название', max_length=200)
    """: A project name."""
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    """: A project description."""
    start_date = models.DateField(verbose_name='Дата начала работы')
    """: A project start date."""
    end_date = models.DateField(verbose_name='Дата завершения')
    """: A project end date."""
    coast = models.DecimalField(verbose_name='Стоимость', max_digits=9, decimal_places=2)
    """: A project's coast."""
    customer = models.ForeignKey(Customer, verbose_name='Заказчик', on_delete=models.SET_NULL, null=True)
    """: A project customer."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.SET_NULL, null=True)
    """: A manager who created the entry."""


    def __str__(self):
        """Return the string representation of the entry."""
        return f'{self.name} ({self.customer})'

    def get_absolute_url(self):
        """Return an url of the record's page."""
        return reverse('project_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['end_date', 'name', 'customer']
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'


class ContactPerson(models.Model):
    """A model for storing a list of contact persons."""
    full_name = models.CharField(verbose_name='Ф.И.О.', max_length=100)
    """: A contact person full name."""
    post = models.CharField(verbose_name='Должность', max_length=50)
    """: A contact person post."""
    customer = models.ForeignKey(Customer, verbose_name='Компания', on_delete=models.CASCADE)
    """: A contact person customer."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.SET_NULL, null=True)
    """: A manager who created the entry."""

    def __str__(self):
        """Return the string representation of the entry."""
        return self.full_name

    class Meta:
        ordering = ['post', 'full_name']
        verbose_name = 'Контактное лицо'
        verbose_name_plural = 'контактные лица'

    def get_absolute_url(self):
        """Return an url of the record's page."""
        return reverse('contact_person_detail', kwargs={'pk': self.pk})


class Contact(models.Model):
    """A model for storing a list of contacts."""
    TYPES = (
        (None, 'Не выбрано'),
        ('e', 'E-mail'),
        ('p', 'Телефон')
    )
    type = models.CharField(verbose_name='Способ связи', max_length=1, choices=TYPES)
    """: A contact type (phone or e-mail)."""
    value = models.CharField(verbose_name='Номер или адрес', max_length=254)
    """: A contact value(phone number or e-mail adress)."""
    company = models.ForeignKey(Customer, verbose_name='Компания', on_delete=models.CASCADE)
    """: A company that owns the contact."""
    contact_person = models.ForeignKey(ContactPerson, verbose_name='Контактное лицо', on_delete=models.CASCADE,
                                       null=True, blank=True)
    """: A contact person that owns the contact."""

    def __str__(self):
        """Return the string representation of the entry."""
        return f'{self.value} ({self.contact_person or self.company})'

    def clean_fields(self, exclude=None):
        """Validate the fields of the contact depending on its type.

        Raises:
            ValidationError: If the value of the field does not resemble the value of the specified type.
        """
        super().clean_fields(exclude=exclude)
        email_pattern = r"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}" \
                        r"[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
        phone_pattern = r"^[+]?[\d \-()]*$"
        if self.type == 'e' and not re.match(email_pattern, self.value ):
            raise ValidationError('Это не похоже на e-mail.')
        elif self.type == 'p' and not re.match(phone_pattern, self.value):
            raise ValidationError(
                'Это не похоже на номер телефона. '
                'Введите что-то типа "+380(012)345-67-89" либо номер в другом разумном формате.'
            )

    class Meta:
        ordering = ['contact_person', 'type']
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Interaction(models.Model):
    """A model for storing a list of interactions with a customers."""
    date = models.DateField(verbose_name='Дата', default=datetime.date.today)
    """: An interaction date."""
    customer = models.ForeignKey(Customer, verbose_name='Заказчик', on_delete=models.SET_NULL, null=True)
    """: A customer."""
    project = models.ForeignKey(Project, verbose_name='Проект', on_delete=models.SET_NULL, null=True)
    """: An interaction project."""
    contact = models.ForeignKey(Contact, verbose_name='Канал связи', on_delete=models.SET_NULL, null=True)
    """: An interaction contact."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.SET_NULL, null=True)
    """: A manager who created the entry."""
    initiator = models.BooleanField(verbose_name='Инициатива заказчика', default=True)
    """: An interaction initiator."""
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    """: An interaction description."""
    GRADES = (
        (-5, -5), (-4, -4), (-3, -3), (-2, -2), (-1, -1),
        (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
    )
    grade = models.SmallIntegerField(verbose_name='Оценка', choices=GRADES)
    """: An interaction grade."""

    def __str__(self):
        """Return the string representation of the entry."""
        return f'{self.project} - {self.date}'

    def get_absolute_url(self):
        """Return an url of the record's page."""
        return reverse('interaction_detail', kwargs={'pk': self.pk})

    def clean_fields(self, exclude=None):
        """Validate the date of interaction.

        Raises:
            ValidationError: If the date of interaction is later than today.
        """
        super().clean_fields(exclude=exclude)
        if self.date > datetime.date.today():
            raise ValidationError({
                'date': 'Дата взаимодействия не может быть позже сегодняшней даты.'
            })

    class Meta:
        ordering = ['-date', '-pk']
        verbose_name = 'Взаимодействие'
        verbose_name_plural = 'Взаимодействия'

crm_project/customers/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import ContactPerson, Contact, Interaction, Project


class DateInputWidget(forms.DateInput):
    input_type = 'date'

    def format_value(self, value):
        return value


class ProjectModelForm(forms.ModelForm):
    """A projects management form."""
    class Meta:
        model = Project
        fields = ['name', 'start_date', 'end_date', 'description', 'coast']
        widgets = {'start_date': DateInputWidget, 'end_date': DateInputWidget}

    def clean_end_date(self):
        """Validation of a project start end end dates.

        Raises:
            ValidationError: If the start date is later than the end date.
        """
        if self.cleaned_data['start_date'] > self.cleaned_data['end_date']:
            raise forms.ValidationError('Дата окончания проекта не может быть ранее даты начала работ.')
        return self.cleaned_data['end_date']


class InteractionForm(forms.ModelForm):
    """An interaction creation form."""
    class Meta:
        model = Interaction
        fields = ['date', 'project', 'contact', 'initiator', 'description', 'grade']
        widgets = {'date': DateInputWidget}


class ContactForm(forms.ModelForm):
    """A contact editing form."""
    class Meta:
        model = Contact
        fields = ['type', 'value', 'contact_person']


ContactFormset = inlineformset_factory(ContactPerson, Contact, fields=['type', 'value'], can_delete=True)
""": A contact creation and edit form."""

crm_project/customers/templates/customers/contact_form.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Сохранить</button>
        <button type="button" onclick="window.history.back()" class="btn btn-secondary">Отмена</button>
    </form>
{% endblock content %}

crm_project/customers/templates/customers/contactperson_form.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form method="post" action="" class="inline_form tags_6"">
        {% csrf_token %}
        {{ form.as_p }}
        <h2>Добавить/редактировать контактные данные</h2>
        <div>{{ contact_formset }}</div>
        <br>
        <button class="btn btn-primary">Сохранить</button>
    </form>
</main>
{% endblock content %}

crm_project/customers/templates/customers/customer_detail.html
{% extends 'base.html' %}

{% block content %}
<main>
    <p><b>Адрес:</b> <i>{{ customer.address }}</i></p>
    <p><b>Создано/изменено:</b> <i>{{ customer.record_created }} / {{ customer.record_last_modified }}</i></p>
    <p><b>Менеджер:</b> {{ customer.manager }}</p>
    <p><b>Описание:</b><br>
        {{ customer.description|safe }}</p>
    {% if user.is_staff %}
    <nav class="navbar navbar-expand-lg">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'customer_update' customer.pk %}">Редактировать</a></li>
            <li class="nav-item"><a class="nav-link" href="" data-bs-toggle="modal"
                                    data-bs-target="#deleteCustomerModal">Удалить</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'project_create' customer.pk %}">Добавить проект</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'interaction_create' customer.pk %}">Добавить взаимодействие</a></li>
        </ul>
    </nav>
    <hr>
    <h2>Контакты</h2>
    {% for contact in company_contacts %}
    <ul>
        <li>{{ contact.value }}
            <a href="{% url 'contact_update' contact.pk %}">
                <i class="bi bi-pencil-square"></i>
            </a>
            <a href="" data-bs-toggle="modal" data-bs-target="#contact{{ contact.pk }}Modal">
                <i class="bi bi-trash"></i>
            </a>
                <!-- DeleteContactModal -->
    <div class="modal fade" id="contact{{ contact.pk }}Modal" tabindex="-1" aria-labelledby="contact{{ contact.pk }}ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="contact{{ contact.pk }}ModalLabel">Подтвердите действие на странице</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'contact_delete' contact.pk %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        Вы действительно хотите удалить контакт<br>«{{ contact }}»?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </ul>
        </li>
    </ul>
    {% endfor %}

    {% for contact_person in customer.contactperson_set.all %}
    <h3>{{ contact_person.full_name }} ({{ contact_person.post }})</h3>
    <ul>
        {% for contact in contact_person.contact_set.all %}
        <li>{{ contact.value }}</li>
        {% endfor %}
        <nav class="navbar navbar-expand-lg">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{{ contact_person.get_absolute_url }}">Смотреть</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'contact_person_update' contact_person.pk %}">Редактировать</a></li>
                <li class="nav-item"><a class="nav-link" href="" data-bs-toggle="modal"
                                        data-bs-target="#contactperson{{ contact_person.pk }}Modal">Удалить</a></li>
            </ul>
        </nav>
        <!-- DeleteContactPersonModal -->
    <div class="modal fade" id="contactperson{{ contact_person.pk }}Modal" tabindex="-1" aria-labelledby="contactperson{{ contact_person.pk }}ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="contactperson{{ contact_person.pk }}ModalLabel">Подтвердите действие на странице</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'contact_person_delete' contact_person.pk %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        Вы действительно хотите удалить контактное лицо<br>«{{ contact_person.full_name }}» ({{ customer.company_name }})?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </ul>
    {% empty %}
    Не указано.<br>
    {% endfor %}
    Добавить <a href="{% url 'contact_person_create' customer.pk %}">Контактное лицо</a> <a href="{% url 'contact_create' customer.pk %}">Контакт</a><br>

    <!-- Modal -->
    <div class="modal fade" id="deleteCustomerModal" tabindex="-1" aria-labelledby="deleteCustomerModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteCustomerModalLabel">Подтвердите действие на странице</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'customer_delete' customer.pk %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        Вы действительно хотите удалить заказчика<br>«{{ customer.company_name }}»?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
    <hr>
    <h2>Проекты</h2>
    {% for project in customer.project_set.all|slice:":5" %}
    <h3>{{ project.name }}</h3>
    <p><b>Сроки выполнения:</b> {{ project.start_date }} - {{ project.end_date }}<br>
    <b>Менеджер:</b> {{ project.manager }}<br>
    <b>Описание:</b> {{ project.description }}<br>
    {% if user.is_staff %}
    <nav class="navbar navbar-expand-lg">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{ project.get_absolute_url }}">Смотреть</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'project_update' project.pk %}">Редактировать</a></li>
            <li class="nav-item"><a class="nav-link" href="" data-bs-toggle="modal"
                                    data-bs-target="#project{{ project.pk }}Modal">Удалить</a></li>
        </ul>
    </nav>
    <!-- Modal -->
    <div class="modal fade" id="project{{ project.pk }}Modal" tabindex="-1" aria-labelledby="project{{ project.pk }}ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="project{{ project.pk }}ModalLabel">Подтвердите действие на странице</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'project_delete' project.pk %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        Вы действительно хотите удалить проект<br>«{{ project.name }}» ({{ project.customer.company_name }})?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endif %}
    {% empty %}
    Проектов пока нет.
    {% endfor %}
    {% if customer.project_set.all.count > 5 %}<a href="{% url 'project_list' customer.pk %}">Смотреть все({{ customer.project_set.all.count }})</a> {% endif %}
    {% if user.is_staff %}<a href="{% url 'project_create' customer.pk %}">Добавить проект</a>
    <hr>
    <h2>Взаимодействия</h2>
    {% if customer.interaction_set.exists %}
    <table class="table interactions">
        <colgroup>
            <col style="width: 100px;">
            <col style="width: auto;">
            <col style="width: 120px;">
            <col style="width: auto;">
            <col style="width: 100px;">
            <col style="width: 80px;">
            <col style="width: 80px;">
        </colgroup>
        <thead>
        <tr>
            <th scope="col">Дата</th>
            <th scope="col">Проект</th>
            <th scope="col">Менеджер</th>
            <th scope="col">Канал связи</th>
            <th scope="col">Инициатор</th>
            <th scope="col">Оценка</th>
            <th scope="col">Действия</th>
        </tr>
        </thead>
        <tbody>
        {% for interaction in customer.interaction_set.all|slice:":5" %}
        <tr>
            <td>{{ interaction.date|date:'d-m-Y' }}</td>
            <td>
                <div>
                    {% if interaction.project %}
                    <a href="{{ interaction.project.get_absolute_url }}">{{ interaction.project.name }}</a>
                    {% else %}
                    Неизвестный проект
                    {% endif %}
                </div>
            </td>
            <td><div>{{ interaction.manager }}</div></td>
            <td><div>{{ interaction.contact }}</div></td>
            <td>{% if interaction.initiator %}Заказчик{% else %}Мы{% endif %}</td>
            <td>{{ interaction.grade }}</td>
            <td>
                <a href="{% url 'interaction_detail' interaction.pk %}"><i class="bi bi-eye-fill"></i></a>
                {% if user.account == interaction.manager %}
                <a href="{% url 'interaction_update' interaction.pk %}"><i class="bi bi-pencil-square"></i></a>
                <a href="" data-bs-toggle="modal"
                                    data-bs-target="#ineraction{{ interaction.pk }}Modal"><i class="bi bi-trash"></i></a>
                {% endif %}
            </td>
        </tr>
        <div class="modal fade" id="ineraction{{ interaction.pk }}Modal" tabindex="-1" aria-labelledby="ineraction{{ interaction.pk }}ModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="ineraction{{ interaction.pk }}ModalLabel">Подтвердите действие на странице</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{% url 'interaction_delete' interaction.pk %}" method="post">
                        {% csrf_token %}
                        <div class="modal-body">
                            Вы действительно хотите удалить взаимодействие<br>«{{ interaction }}»?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                            <button type="submit" class="btn btn-danger">Удалить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    Взаимодействий пока нет.
    {% endif %}
    {% if customer.interaction_set.all.exists %}
    <a href="{% url 'customer_interaction_list' customer.pk %}">Смотреть все ({{ customer.interaction_set.all.count }})</a>
    {% endif %}
    <a href="{% url 'interaction_create' customer.pk%}">Добавить взаимодействие</a></div>
    {% endif %}
</main>
{% endblock content %}

crm_project/customers/templates/customers/customer_form.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-primary">Сохранить</button>
        <button type="button" onclick="window.history.back()" class="btn btn-secondary">Отмена</button>
    </form>
</main>
{% endblock content %}

crm_project/customers/templates/customers/interaction_form.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-primary">Сохранить</button>
        <button type="button" onclick="window.history.back()" class="btn btn-secondary">Отмена</button>
    </form>
</main>
{% endblock content %}

crm_project/customers/templates/customers/project_form.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-primary">Сохранить</button>
        <button type="button" onclick="window.history.back()" class="btn btn-secondary">Отмена</button>
    </form>
</main>
{% endblock content %}