crm_project/accounts/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path

from .views import (
    PassChangeView, ProfileUpdateView,
    UserContactPersonListView, UserCustomerListView,
    UserInteractionListView, UserLoginView,
    UserLogoutView, UserProjectListView,
    KeywordsView
)

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    # path('<int:pk>/private-page/', UserPrivatePageView.as_view(), name='private_page'),
    path('edit-profile/', ProfileUpdateView.as_view(), name='edit_profile'),
    path('change-password/', PassChangeView.as_view(), name='change_password'),
    path('my-customers/', UserCustomerListView.as_view(), name='my_customers'),
    path('my-projects/', UserProjectListView.as_view(), name='my_projects'),
    path('my-contacts/', UserContactPersonListView.as_view(), name='my_contacts'),
    path('my-interactions/', UserInteractionListView.as_view(), name='my_interactions'),
    path('my-keywords/', KeywordsView.as_view(), name='my_keywords'),
]

crm_project/crm_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customers.urls')),
    path('user/', include('accounts.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm_project/accounts/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Account(models.Model):
    """A model for storing extended user accounts."""
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    """: Generic user of a Django."""
    photo = models.ImageField(verbose_name='Фотография', upload_to='photo/', default='photo/no-avatar.png')
    """: A user's photo."""

    def __str__(self):
        """Return the string representation of the entry."""
        return str(self.user.username)

    def get_absolute_url(self):
        """Return the string representation of the entry."""
        return reverse('edit_profile')

    class Meta:
        verbose_name = 'Аккаунт'
        verbose_name_plural = 'Аккаунты'


class Keyword(models.Model):
    """A model for storing user's search keywords."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.CASCADE)
    """: A keyword owner."""
    word = models.CharField(max_length=20)
    """: A keyword."""

    def __str__(self):
        """Return the string representation of the entry."""
        return self.word

    class Meta:
        ordering = ['word']
        verbose_name = 'Ключевое слово'
        verbose_name_plural = 'Ключевые слова'

crm_project/customers/models.py
from ckeditor.fields import RichTextField
import datetime
import re

from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse

from accounts.models import Account


class Customer(models.Model):
    """A model for storing a list of customers."""
    company_name = models.CharField(verbose_name='Название', max_length=200)
    """: The name of a customer's company."""
    address = models.CharField(verbose_name='Адрес', max_length=200, null=True, blank=True)
    """: The address of a customer's company."""
    record_created = models.DateField(verbose_name='Дата создания записи', auto_now_add=True)
    """: Date the record was created."""
    record_last_modified = models.DateField(verbose_name='Дата последнего изменения', auto_now=True)
    """: Date the record was last modified."""
    description = RichTextField(verbose_name='Описание', null=True, blank=True)
    """: Customer description."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.SET_NULL, null=True)
    """: The manager who created the entry."""

    def __str__(self):
        """Return the string representation of the entry."""
        return self.company_name

    def get_absolute_url(self):
        """Return an url of the record's page."""
        return reverse('customer_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-pk']
        verbose_name = 'Заказчик'
        verbose_name_plural = 'Заказчики'


class Project(models.Model):
    """A model for storing a list of projects."""
    name = models.CharField(verbose_name='Название', max_length=200)
    """: A project name."""
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    """: A project description."""
    start_date = models.DateField(verbose_name='Дата начала работы')
    """: A project start date."""
    end_date = models.DateField(verbose_name='Дата завершения')
    """: A project end date."""
    coast = models.DecimalField(verbose_name='Стоимость', max_digits=9, decimal_places=2)
    """: A project's coast."""
    customer = models.ForeignKey(Customer, verbose_name='Заказчик', on_delete=models.SET_NULL, null=True)
    """: A project customer."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.SET_NULL, null=True)
    """: A manager who created the entry."""


    def __str__(self):
        """Return the string representation of the entry."""
        return f'{self.name} ({self.customer})'

    def get_absolute_url(self):
        """Return an url of the record's page."""
        return reverse('project_detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['end_date', 'name', 'customer']
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'


class ContactPerson(models.Model):
    """A model for storing a list of contact persons."""
    full_name = models.CharField(verbose_name='Ф.И.О.', max_length=100)
    """: A contact person full name."""
    post = models.CharField(verbose_name='Должность', max_length=50)
    """: A contact person post."""
    customer = models.ForeignKey(Customer, verbose_name='Компания', on_delete=models.CASCADE)
    """: A contact person customer."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.SET_NULL, null=True)
    """: A manager who created the entry."""

    def __str__(self):
        """Return the string representation of the entry."""
        return self.full_name

    class Meta:
        ordering = ['post', 'full_name']
        verbose_name = 'Контактное лицо'
        verbose_name_plural = 'контактные лица'

    def get_absolute_url(self):
        """Return an url of the record's page."""
        return reverse('contact_person_detail', kwargs={'pk': self.pk})


class Contact(models.Model):
    """A model for storing a list of contacts."""
    TYPES = (
        (None, 'Не выбрано'),
        ('e', 'E-mail'),
        ('p', 'Телефон')
    )
    type = models.CharField(verbose_name='Способ связи', max_length=1, choices=TYPES)
    """: A contact type (phone or e-mail)."""
    value = models.CharField(verbose_name='Номер или адрес', max_length=254)
    """: A contact value(phone number or e-mail adress)."""
    company = models.ForeignKey(Customer, verbose_name='Компания', on_delete=models.CASCADE)
    """: A company that owns the contact."""
    contact_person = models.ForeignKey(ContactPerson, verbose_name='Контактное лицо', on_delete=models.CASCADE,
                                       null=True, blank=True)
    """: A contact person that owns the contact."""

    def __str__(self):
        """Return the string representation of the entry."""
        return f'{self.value} ({self.contact_person or self.company})'

    def clean_fields(self, exclude=None):
        """Validate the fields of the contact depending on its type.

        Raises:
            ValidationError: If the value of the field does not resemble the value of the specified type.
        """
        super().clean_fields(exclude=exclude)
        email_pattern = r"^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}" \
                        r"[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
        phone_pattern = r"^[+]?[\d \-()]*$"
        if self.type == 'e' and not re.match(email_pattern, self.value ):
            raise ValidationError('Это не похоже на e-mail.')
        elif self.type == 'p' and not re.match(phone_pattern, self.value):
            raise ValidationError(
                'Это не похоже на номер телефона. '
                'Введите что-то типа "+380(012)345-67-89" либо номер в другом разумном формате.'
            )

    class Meta:
        ordering = ['contact_person', 'type']
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'


class Interaction(models.Model):
    """A model for storing a list of interactions with a customers."""
    date = models.DateField(verbose_name='Дата', default=datetime.date.today)
    """: An interaction date."""
    customer = models.ForeignKey(Customer, verbose_name='Заказчик', on_delete=models.SET_NULL, null=True)
    """: A customer."""
    project = models.ForeignKey(Project, verbose_name='Проект', on_delete=models.SET_NULL, null=True)
    """: An interaction project."""
    contact = models.ForeignKey(Contact, verbose_name='Канал связи', on_delete=models.SET_NULL, null=True)
    """: An interaction contact."""
    manager = models.ForeignKey(Account, verbose_name='Менеджер', on_delete=models.SET_NULL, null=True)
    """: A manager who created the entry."""
    initiator = models.BooleanField(verbose_name='Инициатива заказчика', default=True)
    """: An interaction initiator."""
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    """: An interaction description."""
    GRADES = (
        (-5, -5), (-4, -4), (-3, -3), (-2, -2), (-1, -1),
        (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
    )
    grade = models.SmallIntegerField(verbose_name='Оценка', choices=GRADES)
    """: An interaction grade."""

    def __str__(self):
        """Return the string representation of the entry."""
        return f'{self.project} - {self.date}'

    def get_absolute_url(self):
        """Return an url of the record's page."""
        return reverse('interaction_detail', kwargs={'pk': self.pk})

    def clean_fields(self, exclude=None):
        """Validate the date of interaction.

        Raises:
            ValidationError: If the date of interaction is later than today.
        """
        super().clean_fields(exclude=exclude)
        if self.date > datetime.date.today():
            raise ValidationError({
                'date': 'Дата взаимодействия не может быть позже сегодняшней даты.'
            })

    class Meta:
        ordering = ['-date', '-pk']
        verbose_name = 'Взаимодействие'
        verbose_name_plural = 'Взаимодействия'

crm_project/accounts/forms.py
from django.contrib.auth.models import User
from django.forms import inlineformset_factory, modelformset_factory

from .models import Account, Keyword
from .services import CustomClearableFileInput

AccountFormSet = inlineformset_factory(
    User, Account, fields=['photo'], can_delete=False, widgets={'photo': CustomClearableFileInput}
)
""": A formset for editing user profile."""

KeywordFormSet = modelformset_factory(Keyword, fields=['word'], labels={'word': 'Слово'}, extra=6, can_delete=True)
""": A keyword management formset."""

crm_project/accounts/templates/accounts/account_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Личный кабинет</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary">Сохранить</button>
        <button type="button" onclick="window.history.back()" class="btn btn-secondary">Отмена</button>
    </form>
{% endblock content %}

crm_project/accounts/templates/accounts/keyword_form.html
{% extends 'base.html' %}
{% block content %}
<main>
    <a href="javascript: window.history.back();">Назад</a>
    <form action="" method="post" class="inline_form tags_4">
        {% csrf_token %}
        <div>
           {{ form }}
        </div>
        <button class="btn btn-primary">Сохранить</button>
    </form>
</main>
{% endblock content %}

crm_project/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="screen-centered">
            <form action="" method="post">
            {% csrf_token %}
                <fieldset>
                    <legend>Авторизация</legend>
                        {{ form }}
                        <button class="btn btn-primary">Войти</button>
                </fieldset>
            </form>
        </div>
    </main>
{% endblock content %}

crm_project/accounts/templates/accounts/password_change_form.html
{% extends 'accounts/user_profile_base.html' %}

{% block user_private_content %}
<form action="" method="post" class="display-block-labels">
    {% csrf_token %}
    {{ form.as_p }}
     <button class="btn btn-primary">Изменить</button>
</form>

{% endblock user_private_content %}

crm_project/accounts/templates/accounts/user_contact_person_list.html
{% extends 'accounts/user_profile_base.html' %}

{% block user_private_content %}
<i>Чтобы добавить контактное лицо, перейдите на страницу его <a href="{% url 'customer_list' %}">компании</a>.</i>
{% for contact_person in contactperson_list %}
<h3>{{ contact_person.full_name }} ({{ contact_person.post }})</h3>
<b>Заказчик:</b> <a href="{{ contact_person.customer.get_absolute_url }}">{{ contact_person.customer }}</a>
<ul>
    {% for contact in contact_person.contact_set.all %}
    <li>{{ contact.value }}</li>
    {% endfor %}
    <nav class="navbar navbar-expand-lg">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{ contact_person.get_absolute_url }}">Смотреть</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'contact_person_update' contact_person.pk %}">Редактировать</a></li>
            <li class="nav-item"><a class="nav-link" href="" data-bs-toggle="modal"
                                    data-bs-target="#contactperson{{ contact_person.pk }}Modal">Удалить</a></li>
            <li class="nav-item"><a class="nav-link" href="{# url 'interaction_create' customer.pk #}">Добавить взаимодействие+</a></li>
        </ul>
    </nav>
    <!-- DeleteContactPersonModal -->
<div class="modal fade" id="contactperson{{ contact_person.pk }}Modal" tabindex="-1" aria-labelledby="contactperson{{ contact_person.pk }}ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="contactperson{{ contact_person.pk }}ModalLabel">Подтвердите действие на странице</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'contact_person_delete' contact_person.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    Вы действительно хотите удалить контактное лицо<br>«{{ contact_person.full_name }}» ({{ customer.company_name }})?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </div>
            </form>
        </div>
    </div>
</div>
</ul>
{% empty %}
Контактных лиц пока нет.<br>
{% endfor %}
{% endblock user_private_content %}

crm_project/accounts/templates/accounts/user_customer_list.html
{% extends 'accounts/user_profile_base.html' %}

{% block user_private_content %}

{% include 'pagination.html' %}
{% for customer in customer_list %}
<h2>{{ customer.company_name }}</h2>
<div><b>Адрес:</b> <i>{{ customer.address }}</i></div>
<div><b>Создано/изменено:</b> <i>{{ customer.record_created }} / {{ customer.record_last_modified }}</i></div>
<div><b>Описание:</b></div>
<div>{{ customer.description|safe|truncatewords:20 }}</div>
<nav class="navbar navbar-expand-lg">
    <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="{{ customer.get_absolute_url }}">Смотреть</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'customer_update' customer.pk %}">Редактировать</a></li>
        <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#customer-{{ customer.pk }}">Удалить</a></li>
    </ul>
</nav>
<!-- Modal -->
<div class="modal fade" id="customer-{{ customer.pk }}" tabindex="-1" aria-labelledby="customer-{{ customer.pk }}Label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="fexampleModalLabel">Подтвердите действие на странице</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'customer_delete' customer.pk %}" method="post">
                {% csrf_token %}
                <div class="modal-body">
                    Вы действительно хотите удалить заказчика <br>«{{ customer.company_name }}»?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                    <button type="submit" class="btn btn-danger">Удалить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endfor %}
{% include 'pagination.html' %}

{% endblock user_private_content %}

crm_project/accounts/templates/accounts/user_interaction_list.html
{% extends 'accounts/user_profile_base.html' %}

{% block user_private_content %}

{% if interaction_list %}
<i>Для добавления нового взаимодействия перейдите на страницу проекта <a href="{% url 'customer_list' %}">заказчика</a> или вашего <a href="{% url 'my_projects' %}">проекта</a>.</i>
<a href="{% url 'my_keywords' %}">Изменить ключевые слова</a>
<div class="keyword-filter"><b>Фильтровать:</b>
{% if keyword_list %}
<form action="" method="get">
    {% for keyword in keyword_list %}
    <input type="checkbox" name="keyword" value="{{ keyword }}"> {{ keyword }}
    {% endfor %}
    <button class="btn btn-primary">Применить</button>
</form>
{% else %}
    Ключевых слов пока нет.
{% endif %}
</div>
{% include 'pagination.html' %}
<table class="table interactions">
    <colgroup>
        <col style="width: 90px;">
        <col style="width: auto;">
        <col style="width: auto;">
        <col style="width: 90px;">
        <col style="width: 70px;">
        <col style="width: 80px;">
    </colgroup>
    <thead>
    <tr>
        <th scope="col">Дата</th>
        <th scope="col">Проект</th>
        <th scope="col">Канал связи</th>
        <th scope="col">Инициатор</th>
        <th scope="col">Оценка</th>
        <th scope="col">Действия</th>
    </tr>
    </thead>
    <tbody>
    {% for interaction in interaction_list %}
    <tr>
        <td>{{ interaction.date|date:'d-m-Y' }}</td>
        <td>
            <div>
                {% if interaction.project %}
                <a href="{{ interaction.project.get_absolute_url }}">{{ interaction.project.name }}</a>
                {% else %}
                Неизвестный проект
                {% endif %}
            </div>
        </td>
        <td>
            <div>{{ interaction.contact }}</div>
        </td>
        <td>{% if interaction.initiator %}Заказчик{% else %}Мы{% endif %}</td>
        <td>{{ interaction.grade }}</td>
        <td>
            <a href="{% url 'interaction_detail' interaction.pk %}"><i class="bi bi-eye-fill"></i></a>
            {% if user.account == interaction.manager %}
            <a href="{% url 'interaction_update' interaction.pk %}"><i class="bi bi-pencil-square"></i></a>
            <a href="" data-bs-toggle="modal"
                                data-bs-target="#ineraction{{ interaction.pk }}Modal"><i class="bi bi-trash"></i></a>
            {% endif %}
        </td>
    </tr>
    <div class="modal fade" id="ineraction{{ interaction.pk }}Modal" tabindex="-1" aria-labelledby="ineraction{{ interaction.pk }}ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ineraction{{ interaction.pk }}ModalLabel">Подтвердите действие на странице</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'interaction_delete' interaction.pk %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        Вы действительно хотите удалить взаимодействие<br>«{{ interaction }}»?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
    </tbody>
</table>
<p>{% include 'pagination.html' %}</p>
{% else %}
Взаимодействия не найдены.
{% endif %}
{% if request.GET.keyword %}<a href="{{ request.path }}">Сбросить фильтры</a><br>{% endif %}

{% endblock user_private_content %}

crm_project/accounts/templates/accounts/user_profile_base.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-3">
<a href="{% url 'edit_profile' %}"{% if request.path == '/user/edit-profile/' %} class="active"{% endif %}>
    Мои данные
</a><br>
<a href="{% url 'change_password' %}"{% if request.path == '/user/change-password/' %} class="active"{% endif %}>
    Изменить пароль
</a><br>
<a href="{% url 'my_customers' %}"{% if request.path == '/user/my-customers/' %} class="active"{% endif %}>
    Мои заказчики
</a><br>
<a href="{% url 'my_projects' %}"{% if request.path == '/user/my-projects/' %} class="active"{% endif %}>
    Мои проекты
</a><br>
<a href="{% url 'my_contacts' %}"{% if request.path == '/user/my-contacts/' %} class="active"{% endif %}>
    Мои контакты
</a><br>
<a href="{% url 'my_interactions' %}"{% if request.path == '/user/my-interactions/' %} class="active"{% endif %}>
    Мои взаимодействия
</a><br>
    </div>
    <div class="col-9">
{% block user_private_content %}{% endblock user_private_content %}
    </div>
  </div>
</div>
{% endblock content %}

crm_project/accounts/templates/accounts/user_profile_form.html
{% extends 'accounts/user_profile_base.html' %}

{% block user_private_content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <img src="/files/{{ object.account.photo }}" class="user-avatar">
    {{ account_formset.as_p }}
    {{ form.as_p }}
    <button class="btn btn-primary">Сохранить</button>
    <button type="button" onclick="window.history.back()" class="btn btn-secondary">Отмена</button>
</form>
{% endblock user_private_content %}

crm_project/accounts/templates/accounts/user_project_list.html
{% extends 'accounts/user_profile_base.html' %}

{% block user_private_content %}

<i>Для добавления нового проекта перейдите на страницу его <a href="{% url 'customer_list' %}">заказчика</a>.</i><br>
    {% for project in project_list %}
    <h2>{{ project.name }}</h2>
    <p><b>Заказчик:</b> <a href="{{ project.customer.get_absolute_url }}">{{ project.customer }}</a></p>
    <p><b>Сроки выполнения:</b> {{ project.start_date }} - {{ project.end_date }}</p>
    <p><b>Описание:</b> {{ project.description }}</p>
    <nav class="navbar navbar-expand-lg">
        <ul class="navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{{ project.get_absolute_url }}">Смотреть</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'project_update' project.pk %}">Редактировать</a></li>
            <li class="nav-item"><a class="nav-link" href="" data-bs-toggle="modal"
                                    data-bs-target="#project-{{ project.pk }}-Modal">Удалить</a></li>
            <li class="nav-item"><a class="nav-link" href="">Добавить взаимодействие*</a></li>
        </ul>
    </nav>
    <!-- Modal -->
    <div class="modal fade" id="project-{{ project.pk }}-Modal" tabindex="-1" aria-labelledby="project-{{ project.pk }}-ModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="project-{{ project.pk }}-ModalLabel">Подтвердите действие на странице</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form action="{% url 'project_delete' project.pk %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">
                        Вы действительно хотите удалить проект<br>«{{ project.name }}» ({{ project.customer.company_name }})?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-danger">Удалить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {% empty %}
    Проектов ещё нет.
    {% endfor %}


    {% include 'pagination.html' %}


{% endblock user_private_content %}